version: '3.8'
services:
  autoqueryai:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      - groq
      - hf
  groq:
    image: groq/groq-api:latest
    ports:
      - "9000:9000"
    environment:
      - GROQ_API_KEY=your_groq_api_key
  hf:
    image: huggingface/text-generation-inference:latest
    ports:
      - "8080:80"
    environment:
      - HF_API_KEY=your_hf_api_key
